include_guard(GLOBAL)

# One independent executable per contract. SOURCES/LIBS/INCLUDES still flow through
# the existing dev-tool helper; no second registry of build dependencies exists.
function(miacode_add_spec NAME)
    cmake_parse_arguments(PARSE_ARGV 1 SPEC ""
        "OWNER;CONTRACT;DOMAIN;KIND;RISK;EXECUTION;STATUS;PLATFORM"
        "SOURCES;LIBS;INCLUDES")
    if(SPEC_UNPARSED_ARGUMENTS OR SPEC_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Spec ${NAME}: unknown arguments or missing values: ${SPEC_UNPARSED_ARGUMENTS};${SPEC_KEYWORDS_MISSING_VALUES}")
    endif()
    foreach(field OWNER CONTRACT DOMAIN KIND RISK EXECUTION STATUS PLATFORM SOURCES)
        if(NOT SPEC_${field})
            message(FATAL_ERROR "Spec ${NAME}: ${field} is required")
        endif()
    endforeach()
    if(NOT EXISTS "${CMAKE_SOURCE_DIR}/${SPEC_OWNER}")
        message(FATAL_ERROR "Spec ${NAME}: missing owner ${SPEC_OWNER}")
    endif()
    if(NOT SPEC_CONTRACT MATCHES "^[a-z0-9][a-z0-9.-]+$")
        message(FATAL_ERROR "Spec ${NAME}: CONTRACT must be a stable lowercase ID")
    endif()
    if(NOT SPEC_KIND MATCHES "^(behavior|integration|source-contract|boundary)$"
       OR NOT SPEC_RISK MATCHES "^(normal|high)$"
       OR NOT SPEC_EXECUTION MATCHES "^(ctest|compile-only)$"
       OR NOT SPEC_STATUS MATCHES "^(active|blocked-link)$"
       OR NOT SPEC_PLATFORM STREQUAL "all")
        message(FATAL_ERROR "Spec ${NAME}: unsupported classification")
    endif()
    if(SPEC_STATUS STREQUAL "blocked-link" AND NOT SPEC_EXECUTION STREQUAL "compile-only")
        message(FATAL_ERROR "Spec ${NAME}: blocked-link cannot register CTest")
    endif()
    set(spec_sources)
    foreach(source IN LISTS SPEC_SOURCES)
        if(NOT source MATCHES "^\\$<" AND NOT EXISTS "${CMAKE_SOURCE_DIR}/${source}")
            message(FATAL_ERROR "Spec ${NAME}: missing source ${source}")
        endif()
        if(source MATCHES "Spec\\.cpp$")
            list(APPEND spec_sources "${source}")
        endif()
    endforeach()
    list(LENGTH spec_sources source_count)
    if(NOT source_count EQUAL 1)
        message(FATAL_ERROR "Spec ${NAME}: exactly one *Spec.cpp is required")
    endif()
    foreach(pair "targets|${NAME}" "sources|${spec_sources}" "contracts|${SPEC_CONTRACT}")
        string(REPLACE "|" ";" pair "${pair}")
        list(GET pair 0 key)
        list(GET pair 1 value)
        get_property(registered GLOBAL PROPERTY MIACODE_SPEC_${key})
        if(value IN_LIST registered)
            message(FATAL_ERROR "Spec ${NAME}: duplicate ${key}: ${value}")
        endif()
        set_property(GLOBAL APPEND PROPERTY MIACODE_SPEC_${key} "${value}")
    endforeach()
    set(test_arg)
    if(SPEC_EXECUTION STREQUAL "ctest")
        set(test_arg TEST)
    endif()
    miacode_add_dev_tool(${NAME} ${test_arg}
        SOURCES ${SPEC_SOURCES} LIBS ${SPEC_LIBS} INCLUDES ${SPEC_INCLUDES})
    if(SPEC_EXECUTION STREQUAL "ctest")
        set_tests_properties(${NAME} PROPERTIES LABELS
            "domain:${SPEC_DOMAIN};kind:${SPEC_KIND};risk:${SPEC_RISK};platform:${SPEC_PLATFORM}")
    endif()
    set_property(GLOBAL APPEND PROPERTY MIACODE_SPEC_CATALOG_ROWS
        "| `${spec_sources}` | `${NAME}` | `${SPEC_OWNER}` | `${SPEC_CONTRACT}` | ${SPEC_DOMAIN} | ${SPEC_KIND} | ${SPEC_RISK} | ${SPEC_PLATFORM} | ${SPEC_EXECUTION} | ${SPEC_STATUS} |\n")
endfunction()

function(miacode_finalize_spec_registry)
    # Scan only to reject missing/orphan registrations, never to populate targets.
    file(GLOB_RECURSE discovered RELATIVE "${CMAKE_SOURCE_DIR}"
        "${CMAKE_SOURCE_DIR}/src/tools/*Spec.cpp")
    get_property(registered GLOBAL PROPERTY MIACODE_SPEC_sources)
    list(SORT discovered)
    list(SORT registered)
    if(NOT "${discovered}" STREQUAL "${registered}")
        set(missing ${discovered})
        set(unexpected ${registered})
        list(REMOVE_ITEM missing ${registered})
        list(REMOVE_ITEM unexpected ${discovered})
        message(FATAL_ERROR "Spec coverage mismatch. Unregistered: ${missing}. Unexpected: ${unexpected}")
    endif()
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        get_property(targets GLOBAL PROPERTY MIACODE_SPEC_targets)
        foreach(target IN LISTS targets)
            if(NOT TARGET ${target})
                message(FATAL_ERROR "Spec ${target}: executable was not created")
            endif()
        endforeach()
    endif()
    if(DEFINED MIACODE_SPEC_CATALOG_OUTPUT)
        get_property(rows GLOBAL PROPERTY MIACODE_SPEC_CATALOG_ROWS)
        list(SORT rows)
        list(JOIN rows "" rows)
        list(LENGTH registered count)
        set(catalog "# Spec catalog\n\nGenerated from `cmake/devtools/specs/` by `cmake -P cmake/devtools/SpecCatalog.cmake`.\nCheck without writing: `cmake -DMIACODE_SPEC_CATALOG_CHECK=ON -P cmake/devtools/SpecCatalog.cmake`.\n\n${count} independent specs; source lists and link dependencies are maintained only in CMake.\nAll existing assertions and target/CTest names are retained. No bundles or retirements.\n\n`platform:all` means the target is registered on every platform, not that all platforms\nhave been tested. Platform-specific source branches and link additions remain in their manifests.\n`blocked-link` records the existing PlaybackCoordinator construction experiment: it is\n`EXCLUDE_FROM_ALL`, has no CTest entry, and its recorded source closure does not link.\nIts `compile-only` execution field does not claim a successful compile/link validation.\nContract IDs are stable identifiers: keep them when renaming a source or target.\nOwners name production modules; kinds describe the checked boundary, not runtime diagnostics.\n\n| Source | Target / CTest name | Owner | Contract | Domain | Kind | Risk | Platform | Execution | Status |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${rows}")
        if(MIACODE_SPEC_CATALOG_CHECK)
            if(NOT EXISTS "${MIACODE_SPEC_CATALOG_OUTPUT}")
                message(FATAL_ERROR "Spec catalog is missing; run cmake -P cmake/devtools/SpecCatalog.cmake")
            endif()
            file(READ "${MIACODE_SPEC_CATALOG_OUTPUT}" existing)
            if(NOT existing STREQUAL catalog)
                message(FATAL_ERROR "Spec catalog is stale; run cmake -P cmake/devtools/SpecCatalog.cmake")
            endif()
        else()
            file(WRITE "${MIACODE_SPEC_CATALOG_OUTPUT}" "${catalog}")
        endif()
    endif()
endfunction()
