#pragma once

#include "../../MainWindow.h"

class QMouseEvent;
class QPoint;
class QPointF;
class QString;

class MainWindow::WindowSection {
public:
    WindowSection(MainWindow& owner, MainWindow::MainWindowUiRefs& ui, MainWindow::MainWindowState& state);

    bool quickShellRootWindowFrameGeometryAvailable() const;
    QRect quickShellRootWindowFrameGeometry() const;
    void setQuickShellRootWindow(QWindow* window);
    void cancelChartAudioDrop();
    void requestShellClose(std::function<void(bool)> onDecided);
    // Everything that happens once the unsaved-changes prompt has said yes.
    // Separate only because it now runs from a continuation.
    bool finishShellClose(QElapsedTimer totalTimer);
    void toggleShellPreviewPlayback();
    void stopShellPreview();
    void seekShellPreview(double second);
    void beginShellPreviewScrub();
    void updateShellPreviewScrub(double second, bool centerView);
    void endShellPreviewScrub(double second, bool centerView);
    void setShellPreviewRate(double rate);
    void toggleShellMuriRenderMode();
    void nudgeShellPreviewRate(int direction);
    bool stepShellPreviewBySeconds(double deltaSeconds, bool centerView);
    void beginShellPreviewHeldSeek(int direction, int key);
    void stopShellPreviewHeldSeek(int key = 0);
    void setShellPreviewFullscreen(bool fullscreen);
    void setShellPreviewPaneWidthRatio(double ratio);
    void setShellBottomTabsHeight(int height);
    void setShellBottomTabsCurrentTab(const QString& tabId);
    void navigateShellTimelineToSecond(double second);
    void wheelShellTimelineNavigate(double second);
    void centerShellTimelineNavigate(double second);
    void shellTimelineDragStarted();
    void shellTimelineDragFinished(double second);
    void shellTimelineUserInteractionStarted();
    void shellTimelineSurfaceReady();
    void shellTimelineFollowPreviewToggled(bool enabled);
    void shellTimelineViewportLockToggled(bool enabled);
    void shellTimelineFollowProgressToggled(bool enabled);
    void shellTimelineSyncToggled(bool enabled);
    bool shellHasShortcut(const QKeySequence& sequence) const;
    bool shellTriggerShortcut(const QKeySequence& sequence);
    QString shellWindowTitle() const;
    bool shellWorkspacePanelsSwapped() const;
    QString shellPreviewSpeedLabel() const;
    bool shellMuriCheckRenderMode() const;
    bool shellPreviewPlaying() const;
    double shellPreviewPositionSeconds() const;
    double shellPreviewDurationSeconds() const;
    QStringList shellPreviewStatsTexts() const;
    double shellPreviewCanvasAspectRatio() const;
    quint64 shellPreviewPaneRestoreGeneration() const;
    double shellPreviewPaneWidthRatio() const;
    bool shellPreviewFullscreen() const;
    QObject* shellPreviewRuntimeObject() const;
    QObject* shellPreviewStageMediaHostObject() const;
    bool shellPreviewUsesSeparateSurface() const;
    QWindow* shellPreviewCompositeWindow() const;
    QObject* shellTimelineStateBridgeObject() const;
    QString shellBottomTabsCurrentTabId() const;
    bool shellBottomTabsVisible() const;
    bool shellTimelineTabVisible() const;
    bool shellValidationTabVisible() const;
    bool shellMuriTabVisible() const;
    bool shellExportPageActive() const;
    QWidget* shellWindowWidget() const;
    QDockWidget* shellOutlineDockWidget() const;
    bool shellOutlineDockCollapsed() const;
    int shellOutlineDockExpandedWidth() const;
    QWidget* shellWorkspaceWidget() const;
    QWidget* shellBottomTabsWidget() const;
    int shellBottomTabsHeight() const;
    double shellBottomTabsHeaderScale() const;
    QWidget* shellPreviewPanelWidget() const;
    double shellNormalizedPreviewCanvasAspectRatio() const;
    void shellRefreshLayoutAfterResize();
    void shellSetRootWindowFrameGeometry(const QRect& geometry);
    void shellNoteQuickUiReady();

    void configureRuntimeDebugOutput();
    void setupInitialWindowGeometry();
    void applyUiTheme();
    void updateOutlineDockCollapseButton();
    void setOutlineDockCollapsed(bool collapsed);
    void applySystemWindowBackdrop(QWidget* target = nullptr) const;
    int computeBottomTabsDeviceHeight() const;
    int computeBottomTabsDeviceHeightForScale(double contentScale) const;
    void applyBottomTabsContentScale();
    void updateBottomTabsDeviceHeight();
    QString formatWindowStateFlags(Qt::WindowStates states) const;
    void logWindowGeometryDebug(const QString& tag, const QString& detail = QString());
    void logTopLevelWindowSnapshot(const QString& tag);
    void closeEvent(QCloseEvent* event);
    void appendOutput(const QString& title, const QString& payload);
    QString describeFocusWidget(QWidget* widget) const;
    QString formatFocusReason(Qt::FocusReason reason) const;
    void logFocusDebug(const QString& reason, QWidget* oldWidget = nullptr, QWidget* nowWidget = nullptr, const QString& detail = QString());
    QTextEdit* activeFindTarget() const;
    bool runFindInEditor(bool backward);
    void updateEditorFindBarGeometry();
    void applyFindOverlayInset();
    void hideFindReplaceBar();
    void onToggleFindReplace();
    void onFindNext();
    void onFindPrevious();
    void onReplaceOne();
    void onReplaceAll();
    QList<QAction*> quickShellShortcutActions() const;
    void refreshQuickShellRehostedWidgetParent(QWidget* widget);
    void setInvalidStarPreviewEasterEggEnabled(bool enabled);
    void ensureInvalidStarPreviewEasterEggSounds();
    void playInvalidStarPreviewEasterEggSound(bool enabled);
    bool eventFilter(QObject* watched, QEvent* event);
    void resizeEvent(QResizeEvent* event);
    void moveEvent(QMoveEvent* event);
    void showEvent(QShowEvent* event);
    void hideEvent(QHideEvent* event);
    bool event(QEvent* event);
    void changeEvent(QEvent* event);

private:
    QTextEdit* resolveRestorableTextEdit(QWidget* widget) const;
    bool isTextInputWidget(QWidget* widget) const;
    bool hasActiveTextInputFocus() const;
    bool shouldRespectFocusedWidgetOnRestore(QWidget* widget, QTextEdit* target) const;
    bool quickShellFocusBridgeActive() const;
    QWindow* previewVisibleHostWindow() const;
    void focusPreviewInteractionTarget(QObject* watched, Qt::FocusReason reason);
    bool touchPadAuthoringEditableContext() const;
    void setHoveredTouchPad(const QString& pad);
    void handleApplicationFocusChanged(QWidget* old, QWidget* now);
    void handleApplicationStateChanged(Qt::ApplicationState state);
    void recoverPreviewBackendsAfterApplicationResume();
    void rememberFocusedTextEditState(QTextEdit* textEdit);
    void rememberFocusedTextEditState();
    void restoreFocusedTextEditState();
    void restoreFocusedTextEditStateAttempt(QPointer<QTextEdit> target, int savedAnchor, int savedPosition, int attempt);
    void clearFocusedTextEditState();
    bool handleChartAudioDropEvent(QObject* watched, QEvent* event);
    void scheduleChartDropOverlayHide();
    void cancelChartDropOverlayHide();
    void setChartDropOverlayVisible(bool visible);

    MainWindow& owner_;
    MainWindow::MainWindowUiRefs& ui_;
    MainWindow::MainWindowState& state_;
    QPointer<QTextEdit> pendingTextFocusWidget_;
    int pendingTextCursorAnchor_ = -1;
    int pendingTextCursorPosition_ = -1;
};
