if(NOT DEFINED SOURCE_DIR OR "${SOURCE_DIR}" STREQUAL "")
    message(FATAL_ERROR "Comic resource SOURCE_DIR is required")
endif()
if(NOT DEFINED DEST_DIR OR "${DEST_DIR}" STREQUAL "")
    message(FATAL_ERROR "Comic resource DEST_DIR is required")
endif()
if(NOT IS_DIRECTORY "${SOURCE_DIR}")
    message(FATAL_ERROR "Comic source directory does not exist: ${SOURCE_DIR}")
endif()

set(source_manifest "${SOURCE_DIR}/manifest.json")
if(NOT EXISTS "${source_manifest}")
    message(FATAL_ERROR "Comic manifest does not exist: ${source_manifest}")
endif()

file(READ "${source_manifest}" manifest_json)
string(JSON manifest_version ERROR_VARIABLE manifest_error GET "${manifest_json}" version)
if(manifest_error OR NOT manifest_version STREQUAL "1")
    message(FATAL_ERROR "Comic manifest version must be integer 1: ${source_manifest}")
endif()
string(JSON manifest_count ERROR_VARIABLE manifest_error LENGTH "${manifest_json}" items)
string(JSON items_type ERROR_VARIABLE items_type_error TYPE "${manifest_json}" items)
if(manifest_error OR items_type_error OR NOT items_type STREQUAL "ARRAY")
    message(FATAL_ERROR "Comic manifest items must be an array: ${source_manifest}")
endif()

set(manifest_names)
set(manifest_keys)
math(EXPR last_manifest_index "${manifest_count} - 1")
if(manifest_count GREATER 0)
    foreach(index RANGE 0 ${last_manifest_index})
        string(JSON item_type ERROR_VARIABLE item_error TYPE "${manifest_json}" items ${index})
        if(item_error OR NOT item_type STREQUAL "OBJECT")
            message(FATAL_ERROR "Comic manifest item ${index} must be an object: ${source_manifest}")
        endif()
        string(JSON file_name ERROR_VARIABLE file_error GET "${manifest_json}" items ${index} file)
        string(JSON width ERROR_VARIABLE width_error GET "${manifest_json}" items ${index} width)
        string(JSON height ERROR_VARIABLE height_error GET "${manifest_json}" items ${index} height)
        if(file_error OR width_error OR height_error)
            message(FATAL_ERROR "Comic manifest items require file, width, and height: ${source_manifest}")
        endif()
        get_filename_component(file_leaf "${file_name}" NAME)
        string(TOLOWER "${file_name}" lower_name)
        get_filename_component(extension "${file_name}" LAST_EXT)
        string(TOLOWER "${extension}" lower_extension)
        if(NOT file_name STREQUAL file_leaf OR file_name STREQUAL ""
            OR file_name MATCHES "\\.\\."
            OR lower_name MATCHES "^comic_001\\.jpg$"
            OR lower_name MATCHES "^fallback\\.jpg$"
            OR NOT lower_extension MATCHES "^\\.(jpg|jpeg|png)$")
            message(FATAL_ERROR "Unsafe or unsupported comic manifest file name '${file_name}': ${source_manifest}")
        endif()
        if(NOT width MATCHES "^[1-9][0-9]*$" OR NOT height MATCHES "^[1-9][0-9]*$")
            message(FATAL_ERROR "Comic manifest dimensions must be positive integers for '${file_name}': ${source_manifest}")
        endif()
        list(FIND manifest_keys "${lower_name}" duplicate_index)
        if(NOT duplicate_index EQUAL -1)
            message(FATAL_ERROR "Comic manifest contains duplicate file name '${file_name}': ${source_manifest}")
        endif()
        list(APPEND manifest_names "${file_name}")
        list(APPEND manifest_keys "${lower_name}")
    endforeach()
endif()

set(source_image_names)
file(GLOB source_entries LIST_DIRECTORIES true "${SOURCE_DIR}/*" "${SOURCE_DIR}/.*")
foreach(source_entry IN LISTS source_entries)
    get_filename_component(file_name "${source_entry}" NAME)
    if(file_name STREQUAL "manifest.json")
        continue()
    endif()
    string(SUBSTRING "${file_name}" 0 1 first_character)
    string(TOLOWER "${file_name}" lower_name)
    get_filename_component(file_extension "${file_name}" LAST_EXT)
    string(TOLOWER "${file_extension}" lower_extension)
    if(IS_DIRECTORY "${source_entry}" OR first_character STREQUAL "."
        OR lower_name MATCHES "(\\.tmp|\\.part|\\.bak)$")
        message(FATAL_ERROR "Illegal comic source entry: ${source_entry}")
    endif()
    if(lower_name MATCHES "^comic_001\\.jpg$" OR lower_name MATCHES "^fallback\\.jpg$")
        continue()
    endif()
    if(NOT lower_extension MATCHES "^\\.(jpg|jpeg|png)$")
        message(FATAL_ERROR "Unsupported comic source entry: ${source_entry}")
    endif()
    list(APPEND source_image_names "${file_name}")
endforeach()

set(source_keys)
foreach(file_name IN LISTS source_image_names)
    string(TOLOWER "${file_name}" lower_name)
    list(FIND source_keys "${lower_name}" duplicate_index)
    if(NOT duplicate_index EQUAL -1)
        message(FATAL_ERROR "Comic source contains duplicate file names differing only by case: '${file_name}'")
    endif()
    list(APPEND source_keys "${lower_name}")
endforeach()
foreach(file_name IN LISTS manifest_names)
    string(TOLOWER "${file_name}" lower_name)
    list(FIND source_keys "${lower_name}" source_index)
    if(source_index EQUAL -1)
        message(FATAL_ERROR "Comic manifest references missing source image '${file_name}': ${source_manifest}")
    endif()
endforeach()
foreach(file_name IN LISTS source_image_names)
    string(TOLOWER "${file_name}" lower_name)
    list(FIND manifest_keys "${lower_name}" manifest_index)
    if(manifest_index EQUAL -1)
        message(FATAL_ERROR "Comic source contains image not listed in manifest '${file_name}': ${source_manifest}")
    endif()
endforeach()

file(MAKE_DIRECTORY "${DEST_DIR}")
file(GLOB destination_entries LIST_DIRECTORIES true "${DEST_DIR}/*" "${DEST_DIR}/.*")
foreach(destination_entry IN LISTS destination_entries)
    file(REMOVE_RECURSE "${destination_entry}")
endforeach()
file(COPY_FILE "${source_manifest}" "${DEST_DIR}/manifest.json")
foreach(file_name IN LISTS manifest_names)
    file(COPY_FILE "${SOURCE_DIR}/${file_name}" "${DEST_DIR}/${file_name}")
endforeach()

list(LENGTH manifest_names resource_count)
message(STATUS "Comic source directory: ${SOURCE_DIR}")
message(STATUS "Comic destination directory: ${DEST_DIR}")
message(STATUS "Comic manifest: ${source_manifest}")
message(STATUS "Comic resource count: ${resource_count}")
